use serde::{Deserialize, Serialize};

use super::player::Player;

// ---------------------------------------------------------------------------
// PlayerMetric enum — generated by macro from a single data table
// ---------------------------------------------------------------------------

macro_rules! define_player_metrics {
    ($(
        $variant:ident : $display:literal => |$player:ident| $expr:expr
    ),* $(,)?) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
        #[serde(rename_all = "SCREAMING_SNAKE_CASE")]
        pub enum PlayerMetric {
            $($variant),*
        }

        impl PlayerMetric {
            /// Human-readable label for this metric.
            pub fn display_name(&self) -> &'static str {
                match self {
                    $(Self::$variant => $display),*
                }
            }

            /// Extract the numeric value from a player record.
            /// Returns `None` when the metric is unavailable.
            pub fn extract(&self, player: &Player) -> Option<f64> {
                match self {
                    $(Self::$variant => { let $player = player; $expr }),*
                }
            }

            /// Return all variants in definition order.
            pub fn all_variants() -> Vec<PlayerMetric> {
                vec![$(Self::$variant),*]
            }
        }
    };
}

define_player_metrics! {
    // ══════════ Attacking ══════════
    Goals:                    "Goals"                     => |p| Some(p.goals as f64),
    GoalsPer90:               "Goals per 90"              => |p| p.goals_per_90,
    GoalsOutsideBox:          "Goals Outside Box"         => |p| Some(p.goals_outside_box as f64),
    GoalsOutsideBoxPer90:     "Goals Outside Box per 90"  => |p| p.goals_outside_box_per_90,
    Xg:                       "xG"                        => |p| Some(p.xg),
    XgPer90:                  "xG per 90"                 => |p| p.xg_per_90,
    Npxg:                     "NPxG"                      => |p| Some(p.npxg),
    NpxgPer90:                "NPxG per 90"               => |p| p.npxg_per_90,
    XgOverperformance:        "xG Overperformance"        => |p| Some(p.xg_overperformance),
    XgOverperformancePer90:   "xG Overperformance per 90" => |p| p.xg_overperformance_per_90,
    XgPerShot:                "xG per Shot"               => |p| Some(p.xg_per_shot),
    Shots:                    "Shots"                     => |p| Some(p.shots as f64),
    ShotsPer90:               "Shots per 90"              => |p| p.shots_per_90,
    ShotsOutsideBox:          "Shots Outside Box"         => |p| p.shots_outside_box.map(|v| v as f64),
    ShotsOutsideBoxPer90:     "Shots Outside Box per 90"  => |p| p.shots_outside_box_per_90,
    ShotsOnTarget:            "Shots on Target"           => |p| Some(p.shots_on_target as f64),
    ShotsOnTargetPer90:       "Shots on Target per 90"    => |p| p.shots_on_target_per_90,
    ShotsOnTargetRatio:       "Shots on Target Ratio"     => |p| p.shots_on_target_ratio,
    ConversionRatio:          "Conversion Ratio"          => |p| p.conversion_ratio,
    PensTaken:                "Pens Taken"                => |p| Some(p.pens_taken as f64),
    PensTakenPer90:           "Pens Taken per 90"         => |p| p.pens_taken_per_90,
    PensScored:               "Pens Scored"               => |p| Some(p.pens_scored as f64),
    PensScoredPer90:          "Pens Scored per 90"        => |p| p.pens_scored_per_90,
    PensScoredRatio:          "Pens Scored Ratio"         => |p| p.pens_scored_ratio,
    FreeKickShots:            "Free Kick Shots"           => |p| Some(p.free_kick_shots as f64),
    FreeKickShotsPer90:       "Free Kick Shots per 90"    => |p| p.free_kick_shots_per_90,
    MinutesPerGoal:           "Minutes per Goal"          => |p| p.minutes_per_goal,
    MinutesPerGoalOrAssist:   "Minutes per Goal or Assist"=> |p| p.minutes_per_goal_or_assist,
    MinutesPerAssist:         "Minutes per Assist"        => |p| p.minutes_per_assist,

    // ══════════ Creativity ══════════
    Assists:                  "Assists"                   => |p| Some(p.assists as f64),
    AssistsPer90:             "Assists per 90"            => |p| p.assists_per_90,
    Xa:                       "xA"                        => |p| Some(p.xa),
    XaPer90:                  "xA per 90"                 => |p| p.xa_per_90,
    ChancesCreated:           "Chances Created"           => |p| p.chances_created.map(|v| v as f64),
    ChancesCreatedPer90:      "Chances Created per 90"    => |p| p.chances_created_per_90,
    ClearCutChances:          "Clear Cut Chances"         => |p| Some(p.clear_cut_chances as f64),
    ClearCutChancesPer90:     "Clear Cut Chances per 90"  => |p| p.clear_cut_chances_per_90,
    KeyPasses:                "Key Passes"                => |p| Some(p.key_passes as f64),
    KeyPassesPer90:           "Key Passes per 90"         => |p| p.key_passes_per_90,
    OpKeyPasses:              "OP Key Passes"             => |p| p.op_key_passes.map(|v| v as f64),
    OpKeyPassesPer90:         "OP Key Passes per 90"      => |p| p.op_key_passes_per_90,
    CrossesAttempted:         "Crosses Attempted"         => |p| Some(p.crosses_attempted as f64),
    CrossesAttemptedPer90:    "Crosses Attempted per 90"  => |p| p.crosses_attempted_per_90,
    CrossesCompleted:         "Crosses Completed"         => |p| Some(p.crosses_completed as f64),
    CrossesCompletedPer90:    "Crosses Completed per 90"  => |p| p.crosses_completed_per_90,
    CrossCompletionRatio:     "Cross Completion Ratio"    => |p| p.cross_completion_ratio,
    OpCrossesAttempted:       "OP Crosses Attempted"      => |p| Some(p.op_crosses_attempted as f64),
    OpCrossesAttemptedPer90:  "OP Crosses Attempted per 90" => |p| p.op_crosses_attempted_per_90,
    OpCrossesCompleted:       "OP Crosses Completed"      => |p| Some(p.op_crosses_completed as f64),
    OpCrossesCompletedPer90:  "OP Crosses Completed per 90" => |p| p.op_crosses_completed_per_90,
    OpCrossCompletionRatio:   "OP Cross Completion Ratio" => |p| p.op_cross_completion_ratio,

    // ══════════ Transition ══════════
    PassesAttempted:          "Passes Attempted"          => |p| Some(p.passes_attempted as f64),
    PassesAttemptedPer90:     "Passes Attempted per 90"   => |p| p.passes_attempted_per_90,
    PassesCompleted:          "Passes Completed"          => |p| Some(p.passes_completed as f64),
    PassesCompletedPer90:     "Passes Completed per 90"   => |p| p.passes_completed_per_90,
    PassCompletionRatio:      "Pass Completion Ratio"     => |p| p.pass_completion_ratio,
    ProgressivePasses:        "Progressive Passes"        => |p| Some(p.progressive_passes as f64),
    ProgressivePassesPer90:   "Progressive Passes per 90" => |p| p.progressive_passes_per_90,
    Dribbles:                 "Dribbles"                  => |p| Some(p.dribbles as f64),
    DribblesPer90:            "Dribbles per 90"           => |p| p.dribbles_per_90,
    DistanceCovered:          "Distance Covered"          => |p| Some(p.distance_covered as f64),
    DistanceCoveredPer90:     "Distance Covered per 90"   => |p| p.distance_covered_per_90,
    Sprints:                  "Sprints"                   => |p| p.sprints.map(|v| v as f64),
    SprintsPer90:             "Sprints per 90"            => |p| p.sprints_per_90,
    PossLost:                 "Possession Lost"           => |p| p.poss_lost.map(|v| v as f64),
    PossLostPer90:            "Possession Lost per 90"    => |p| p.poss_lost_per_90,

    // ══════════ Defensive ══════════
    TacklesAttempted:         "Tackles Attempted"         => |p| Some(p.tackles_attempted as f64),
    TacklesAttemptedPer90:    "Tackles Attempted per 90"  => |p| p.tackles_attempted_per_90,
    TacklesCompleted:         "Tackles Completed"         => |p| Some(p.tackles_completed as f64),
    TacklesCompletedPer90:    "Tackles Completed per 90"  => |p| p.tackles_completed_per_90,
    TackleCompletionRatio:    "Tackle Completion Ratio"   => |p| p.tackle_completion_ratio,
    KeyTackles:               "Key Tackles"               => |p| Some(p.key_tackles as f64),
    KeyTacklesPer90:          "Key Tackles per 90"        => |p| p.key_tackles_per_90,
    Interceptions:            "Interceptions"             => |p| Some(p.interceptions as f64),
    InterceptionsPer90:       "Interceptions per 90"      => |p| p.interceptions_per_90,
    PossWon:                  "Possession Won"            => |p| p.poss_won.map(|v| v as f64),
    PossWonPer90:             "Possession Won per 90"     => |p| p.poss_won_per_90,
    PressuresAttempted:       "Pressures Attempted"       => |p| Some(p.pressures_attempted as f64),
    PressuresAttemptedPer90:  "Pressures Attempted per 90"=> |p| p.pressures_attempted_per_90,
    PressuresCompleted:       "Pressures Completed"       => |p| Some(p.pressures_completed as f64),
    PressuresCompletedPer90:  "Pressures Completed per 90"=> |p| p.pressures_completed_per_90,
    PressureSuccessRatio:     "Pressure Success Ratio"    => |p| p.pressure_success_ratio,
    Blocks:                   "Blocks"                    => |p| Some(p.blocks as f64),
    BlocksPer90:              "Blocks per 90"             => |p| p.blocks_per_90,
    ShotsBlocked:             "Shots Blocked"             => |p| Some(p.shots_blocked as f64),
    ShotsBlockedPer90:        "Shots Blocked per 90"      => |p| p.shots_blocked_per_90,
    Clearances:               "Clearances"                => |p| Some(p.clearances as f64),
    ClearancesPer90:          "Clearances per 90"         => |p| p.clearances_per_90,

    // ══════════ Aerial ══════════
    HeadersAttempted:         "Headers Attempted"         => |p| Some(p.headers_attempted as f64),
    HeadersAttemptedPer90:    "Headers Attempted per 90"  => |p| p.headers_attempted_per_90,
    HeadersWon:               "Headers Won"               => |p| Some(p.headers_won as f64),
    HeadersWonPer90:          "Headers Won per 90"        => |p| p.headers_won_per_90,
    HeadersLost:              "Headers Lost"              => |p| p.headers_lost.map(|v| v as f64),
    HeadersLostPer90:         "Headers Lost per 90"       => |p| p.headers_lost_per_90,
    HeadersWonRatio:          "Headers Won Ratio"         => |p| p.headers_won_ratio,
    KeyHeaders:               "Key Headers"               => |p| p.key_headers.map(|v| v as f64),
    KeyHeadersPer90:          "Key Headers per 90"        => |p| p.key_headers_per_90,

    // ══════════ Goalkeeping ══════════
    CleanSheets:              "Clean Sheets"              => |p| Some(p.clean_sheets as f64),
    CleanSheetsPer90:         "Clean Sheets per 90"       => |p| p.clean_sheets_per_90,
    GoalsConceded:            "Goals Conceded"            => |p| Some(p.goals_conceded as f64),
    GoalsConcededPer90:       "Goals Conceded per 90"     => |p| p.goals_conceded_per_90,
    TotalSaves:               "Total Saves"               => |p| p.total_saves.map(|v| v as f64),
    TotalSavesPer90:          "Total Saves per 90"        => |p| p.total_saves_per_90,
    SaveRatio:                "Save Ratio"                => |p| p.save_ratio,
    XsvPercent:               "xSV%"                      => |p| Some(p.xsv_percent),
    Xgp:                      "xGP"                       => |p| Some(p.xgp),
    XgpPer90:                 "xGP per 90"                => |p| p.xgp_per_90,
    SavesHeld:                "Saves Held"                => |p| Some(p.saves_held as f64),
    SavesHeldPer90:           "Saves Held per 90"         => |p| p.saves_held_per_90,
    SavesParried:             "Saves Parried"             => |p| Some(p.saves_parried as f64),
    SavesParriedPer90:        "Saves Parried per 90"      => |p| p.saves_parried_per_90,
    SavesTipped:              "Saves Tipped"              => |p| Some(p.saves_tipped as f64),
    SavesTippedPer90:         "Saves Tipped per 90"       => |p| p.saves_tipped_per_90,
    PensFaced:                "Pens Faced"                => |p| Some(p.pens_faced as f64),
    PensFacedPer90:           "Pens Faced per 90"         => |p| p.pens_faced_per_90,
    PensSaved:                "Pens Saved"                => |p| Some(p.pens_saved as f64),
    PensSavedPer90:           "Pens Saved per 90"         => |p| p.pens_saved_per_90,
    PensSavedRatio:           "Pens Saved Ratio"          => |p| p.pens_saved_ratio,

    // ══════════ Discipline ══════════
    FoulsMade:                "Fouls Made"                => |p| Some(p.fouls_made as f64),
    FoulsMadePer90:           "Fouls Made per 90"         => |p| p.fouls_made_per_90,
    FoulsAgainst:             "Fouls Against"             => |p| Some(p.fouls_against as f64),
    FoulsAgainstPer90:        "Fouls Against per 90"      => |p| p.fouls_against_per_90,
    YellowCards:              "Yellow Cards"              => |p| Some(p.yellow_cards as f64),
    YellowCardsPer90:         "Yellow Cards per 90"       => |p| p.yellow_cards_per_90,
    RedCards:                 "Red Cards"                 => |p| Some(p.red_cards as f64),
    RedCardsPer90:            "Red Cards per 90"          => |p| p.red_cards_per_90,
    Offsides:                 "Offsides"                  => |p| Some(p.offsides as f64),
    OffsidesPer90:            "Offsides per 90"           => |p| p.offsides_per_90,
    Mlg:                      "MLG"                       => |p| Some(p.mlg as f64),
    MlgPer90:                 "MLG per 90"                => |p| p.mlg_per_90,

    // ══════════ Match Impact ══════════
    Rating:                   "Rating"                    => |p| Some(p.rating),
    Pom:                      "POM"                       => |p| Some(p.pom as f64),
    GameWinRatio:             "Game Win Ratio"            => |p| p.game_win_ratio,

    // ══════════ Derived ══════════
    CleanSheetsRatio:         "Clean Sheets Ratio"        => |p| {
        let games = p.games_won + p.games_drawn + p.games_lost;
        (games > 0).then(|| p.clean_sheets as f64 / games as f64)
    },
}

// ---------------------------------------------------------------------------
// Phase
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Phase {
    InPossession,
    OutOfPossession,
}

// ---------------------------------------------------------------------------
// ArchetypeMetric
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ArchetypeMetric {
    pub metric: PlayerMetric,
    pub weight: f64,
    pub inverted: bool,
}

// ---------------------------------------------------------------------------
// Archetype
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Archetype {
    pub id: String,
    pub position: String,
    pub phase: Phase,
    pub name: String,
    pub tags: Vec<String>,
    pub description: String,
    pub metrics: Vec<ArchetypeMetric>,
    pub is_user_created: bool,
}

impl Archetype {
    /// Generate a stable ID: `{position}/{phase}/{name}` in kebab-case.
    pub fn generate_id(position: &str, phase: Phase, name: &str) -> String {
        let phase_str = match phase {
            Phase::InPossession => "in-possession",
            Phase::OutOfPossession => "out-of-possession",
        };
        let name_slug = name.to_lowercase().replace(' ', "-");
        format!(
            "{}/{}/{}",
            position.to_lowercase().replace(' ', "-"),
            phase_str,
            name_slug
        )
    }
}

// ---------------------------------------------------------------------------
// MetricInfo — lightweight descriptor for the UI
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MetricInfo {
    pub id: PlayerMetric,
    pub display_name: String,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Every variant should have a non-empty display name.
    #[test]
    fn all_metrics_have_display_names() {
        for variant in PlayerMetric::all_variants() {
            let name = variant.display_name();
            assert!(!name.is_empty(), "display_name() returned empty for {variant:?}");
        }
    }

    /// Build a minimal Player with all per-90 fields populated.
    fn sample_player() -> Player {
        Player {
            goals_per_90: Some(0.5),
            goals_outside_box_per_90: Some(0.1),
            xg_per_90: Some(0.45),
            npxg_per_90: Some(0.40),
            xg_overperformance_per_90: Some(0.05),
            xg_per_shot: 0.12,
            shots_per_90: Some(3.0),
            shots_outside_box_per_90: Some(1.0),
            shots_on_target_per_90: Some(1.5),
            shots_on_target_ratio: Some(0.5),
            conversion_ratio: Some(0.1667),
            pens_taken_per_90: Some(0.1),
            pens_scored_per_90: Some(0.08),
            pens_scored_ratio: Some(0.8),
            free_kick_shots_per_90: Some(0.2),
            minutes_per_goal: Some(180.0),
            minutes_per_goal_or_assist: Some(120.0),
            minutes_per_assist: Some(360.0),
            assists_per_90: Some(0.3),
            xa_per_90: Some(0.25),
            chances_created_per_90: Some(2.0),
            clear_cut_chances_per_90: Some(0.5),
            key_passes_per_90: Some(1.0),
            op_key_passes_per_90: Some(0.8),
            crosses_attempted_per_90: Some(4.0),
            crosses_completed_per_90: Some(1.2),
            cross_completion_ratio: Some(0.3),
            op_crosses_attempted_per_90: Some(3.0),
            op_crosses_completed_per_90: Some(0.9),
            op_cross_completion_ratio: Some(0.3),
            passes_attempted_per_90: Some(50.0),
            passes_completed_per_90: Some(42.0),
            pass_completion_ratio: Some(0.84),
            progressive_passes_per_90: Some(8.0),
            dribbles_per_90: Some(2.5),
            distance_covered_per_90: Some(10.5),
            sprints_per_90: Some(15.0),
            sprints: Some(45),
            poss_lost_per_90: Some(5.0),
            tackles_attempted_per_90: Some(3.0),
            tackles_completed_per_90: Some(2.2),
            tackle_completion_ratio: Some(0.733),
            key_tackles_per_90: Some(0.5),
            interceptions_per_90: Some(1.5),
            poss_won_per_90: Some(2.0),
            pressures_attempted_per_90: Some(12.0),
            pressures_completed_per_90: Some(4.0),
            pressure_success_ratio: Some(0.333),
            blocks_per_90: Some(1.0),
            shots_blocked_per_90: Some(0.5),
            clearances_per_90: Some(4.0),
            headers_attempted_per_90: Some(5.0),
            headers_won_per_90: Some(3.0),
            headers_lost_per_90: Some(2.0),
            headers_won_ratio: Some(0.6),
            key_headers_per_90: Some(1.0),
            clean_sheets_per_90: Some(0.3),
            goals_conceded_per_90: Some(1.2),
            total_saves_per_90: Some(3.0),
            save_ratio: Some(0.714),
            xsv_percent: 0.5,
            xgp_per_90: Some(1.1),
            saves_held_per_90: Some(1.5),
            saves_parried_per_90: Some(0.8),
            saves_tipped_per_90: Some(0.7),
            pens_faced_per_90: Some(0.2),
            pens_saved_per_90: Some(0.1),
            pens_saved_ratio: Some(0.5),
            fouls_made_per_90: Some(1.0),
            fouls_against_per_90: Some(1.5),
            yellow_cards_per_90: Some(0.2),
            red_cards_per_90: Some(0.01),
            offsides_per_90: Some(0.3),
            mlg_per_90: Some(0.5),
            rating: 7.2,
            pom: 3,
            game_win_ratio: Some(0.55),
            games_won: 10,
            games_drawn: 5,
            games_lost: 5,
            clean_sheets: 6,
            // raw counts
            goals: 15,
            goals_outside_box: 3,
            xg: 12.0,
            npxg: 11.0,
            xg_overperformance: 1.0,
            shots: 100,
            shots_outside_box: Some(30),
            shots_on_target: 50,
            pens_taken: 2,
            pens_scored: 2,
            free_kick_shots: 5,
            assists: 8,
            xa: 7.0,
            chances_created: Some(50),
            clear_cut_chances: 10,
            key_passes: 25,
            op_key_passes: Some(20),
            crosses_attempted: 80,
            crosses_completed: 25,
            op_crosses_attempted: 60,
            op_crosses_completed: 18,
            passes_attempted: 1200,
            passes_completed: 1000,
            progressive_passes: 200,
            dribbles: 60,
            distance_covered: 11000,
            poss_lost: Some(120),
            tackles_attempted: 60,
            tackles_completed: 45,
            key_tackles: 12,
            interceptions: 35,
            poss_won: Some(50),
            pressures_attempted: 300,
            pressures_completed: 100,
            blocks: 25,
            shots_blocked: 12,
            clearances: 100,
            headers_attempted: 120,
            headers_won: 70,
            headers_lost: Some(50),
            key_headers: Some(25),
            goals_conceded: 15,
            total_saves: Some(60),
            xgp: 14.0,
            saves_held: 30,
            saves_parried: 15,
            saves_tipped: 15,
            pens_faced: 5,
            pens_saved: 2,
            fouls_made: 25,
            fouls_against: 35,
            yellow_cards: 5,
            red_cards: 1,
            offsides: 8,
            mlg: 12,
            ..Default::default()
        }
    }

    #[test]
    fn extract_direct_option_fields() {
        let player = sample_player();
        assert_eq!(PlayerMetric::GoalsPer90.extract(&player), Some(0.5));
        assert_eq!(PlayerMetric::AssistsPer90.extract(&player), Some(0.3));
        assert_eq!(PlayerMetric::PassCompletionRatio.extract(&player), Some(0.84));
    }

    #[test]
    fn extract_non_option_fields() {
        let player = sample_player();
        // These fields are non-option f64, wrapped in Some()
        assert_eq!(PlayerMetric::Rating.extract(&player), Some(7.2));
        assert_eq!(PlayerMetric::XgPerShot.extract(&player), Some(0.12));
        assert_eq!(PlayerMetric::XsvPercent.extract(&player), Some(0.5));
    }

    #[test]
    fn extract_u16_cast_fields() {
        let player = sample_player();
        assert_eq!(PlayerMetric::Pom.extract(&player), Some(3.0));
    }

    #[test]
    fn extract_option_u16_fields() {
        let player = sample_player();
        assert_eq!(PlayerMetric::Sprints.extract(&player), Some(45.0));

        // Player with sprints = None
        let no_sprints = Player::default();
        assert_eq!(PlayerMetric::Sprints.extract(&no_sprints), None);
    }

    #[test]
    fn extract_none_for_unavailable_metrics() {
        // Default player has all Option fields = None
        let player = Player::default();
        assert_eq!(PlayerMetric::GoalsPer90.extract(&player), None);
        assert_eq!(PlayerMetric::Rating.extract(&player), Some(0.0)); // non-option, defaults to 0.0
    }

    #[test]
    fn extract_clean_sheets_ratio() {
        // Player with games
        let player = sample_player();
        let expected = Some(6.0 / 20.0); // 6 clean sheets in 20 games
        assert_eq!(PlayerMetric::CleanSheetsRatio.extract(&player), expected);

        // Player with no games
        let no_games = Player::default();
        assert_eq!(PlayerMetric::CleanSheetsRatio.extract(&no_games), None);
    }

    #[test]
    fn generate_id_expected_format() {
        let id = Archetype::generate_id("Goalkeeper", Phase::InPossession, "Ball-Playing Goalkeeper");
        assert_eq!(id, "goalkeeper/in-possession/ball-playing-goalkeeper");
    }

    #[test]
    fn generate_id_multiple_words() {
        let id = Archetype::generate_id("Central Defender", Phase::OutOfPossession, "No-Nonsense CB");
        assert_eq!(id, "central-defender/out-of-possession/no-nonsense-cb");
    }

    #[test]
    fn phase_serialization() {
        let in_poss = serde_json::to_string(&Phase::InPossession).unwrap();
        assert_eq!(in_poss, "\"in-possession\"");

        let out_of_poss = serde_json::to_string(&Phase::OutOfPossession).unwrap();
        assert_eq!(out_of_poss, "\"out-of-possession\"");
    }

    #[test]
    fn player_metric_serde_roundtrip() {
        let val = PlayerMetric::GoalsPer90;
        let json = serde_json::to_string(&val).unwrap();
        // serde rename_all = "SCREAMING_SNAKE_CASE" converts GoalsPer90
        assert_eq!(json, "\"GOALS_PER90\"");

        let back: PlayerMetric = serde_json::from_str(&json).unwrap();
        assert_eq!(back, PlayerMetric::GoalsPer90);
    }

    #[test]
    fn player_metric_xg_per_shot_serialization() {
        // "XgPerShot" -> "XG_PER_SHOT" — ensure multi-capital handling
        let val = PlayerMetric::XgPerShot;
        let json = serde_json::to_string(&val).unwrap();
        assert_eq!(json, "\"XG_PER_SHOT\"");

        let back: PlayerMetric = serde_json::from_str(&json).unwrap();
        assert_eq!(back, PlayerMetric::XgPerShot);
    }

    #[test]
    fn extract_raw_u16_fields() {
        let player = sample_player();
        assert_eq!(PlayerMetric::Goals.extract(&player), Some(15.0));
        assert_eq!(PlayerMetric::Shots.extract(&player), Some(100.0));
        assert_eq!(PlayerMetric::PassesAttempted.extract(&player), Some(1200.0));
        assert_eq!(PlayerMetric::TacklesAttempted.extract(&player), Some(60.0));
    }

    #[test]
    fn extract_raw_u32_fields() {
        let player = sample_player();
        assert_eq!(PlayerMetric::DistanceCovered.extract(&player), Some(11000.0));
    }

    #[test]
    fn extract_raw_f64_fields() {
        let player = sample_player();
        assert_eq!(PlayerMetric::Xg.extract(&player), Some(12.0));
        assert_eq!(PlayerMetric::Npxg.extract(&player), Some(11.0));
        assert_eq!(PlayerMetric::Xa.extract(&player), Some(7.0));
        assert_eq!(PlayerMetric::Xgp.extract(&player), Some(14.0));
    }

    #[test]
    fn extract_raw_option_u16_fields() {
        let player = sample_player();
        assert_eq!(PlayerMetric::ShotsOutsideBox.extract(&player), Some(30.0));
        assert_eq!(PlayerMetric::HeadersLost.extract(&player), Some(50.0));
        assert_eq!(PlayerMetric::KeyHeaders.extract(&player), Some(25.0));

        // Fields that are None in default
        let def = Player::default();
        assert_eq!(PlayerMetric::ShotsOutsideBox.extract(&def), None);
    }

    #[test]
    fn total_variant_count() {
        // Verifies all metric fields from Player are covered in the macro.
        let count = PlayerMetric::all_variants().len();
        assert!(count >= 130, "only {count} variants defined, expected at least 130");
    }

    #[test]
    fn archetype_struct_serde_roundtrip() {
        let arch = Archetype {
            id: "test/id".into(),
            position: "Test".into(),
            phase: Phase::InPossession,
            name: "Test Archetype".into(),
            tags: vec!["tag1".into()],
            description: "A test".into(),
            metrics: vec![ArchetypeMetric {
                metric: PlayerMetric::GoalsPer90,
                weight: 1.0,
                inverted: false,
            }],
            is_user_created: true,
        };

        let json = serde_json::to_string(&arch).unwrap();
        // Verify camelCase keys
        assert!(json.contains("\"isUserCreated\""));

        let back: Archetype = serde_json::from_str(&json).unwrap();
        assert_eq!(back.id, "test/id");
        assert_eq!(back.metrics.len(), 1);
        assert!(back.is_user_created);
    }

    #[test]
    fn all_serde_values_unique() {
        let mut seen = std::collections::HashSet::new();
        for v in PlayerMetric::all_variants() {
            let json = serde_json::to_string(&v).unwrap();
            assert!(seen.insert(json.clone()), "duplicate serde value: {json}");
        }
    }
}

