use serde::{Deserialize, Serialize};

/// FM player with all stats and computed per-90 metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Player {
    // === Identity fields ===
    pub unique_id: u64,
    pub name: String,
    pub nation: String,
    pub second_nation: Option<String>,
    pub club: String,
    pub position: String,
    /// Parsed granular position codes (e.g. ["DL", "DC", "WBL"])
    pub positions: Vec<String>,

    // === Physical fields ===
    pub age: u8,
    pub height_cm: u16,
    pub left_foot: crate::models::types::FootRating,
    pub right_foot: crate::models::types::FootRating,

    // === Ability fields ===
    pub current_ability: u8,
    pub potential_ability: u8,

    // === Contract fields ===
    pub transfer_value: crate::models::types::TransferValue,
    pub weekly_wage: crate::models::types::Wage,
    pub contract_expires: Option<chrono::NaiveDate>,

    // === Availability ===
    pub appearances: crate::models::types::Appearances,
    pub minutes: u32,

    // === Attacking metrics ===
    pub goals: u16,
    pub goals_per_90: Option<f64>,
    pub goals_outside_box: u16,
    pub goals_outside_box_per_90: Option<f64>,
    pub xg: f64,
    pub xg_per_90: Option<f64>,
    pub npxg: f64,
    pub npxg_per_90: Option<f64>,
    pub xg_overperformance: f64,
    pub xg_overperformance_per_90: Option<f64>,
    pub xg_per_shot: f64,
    pub shots: u16,
    pub shots_per_90: Option<f64>,
    pub shots_outside_box: Option<u16>,
    pub shots_outside_box_per_90: Option<f64>,
    pub shots_on_target: u16,
    pub shots_on_target_per_90: Option<f64>,
    pub shots_on_target_ratio: Option<f64>,
    pub conversion_ratio: Option<f64>,
    pub pens_taken: u16,
    pub pens_taken_per_90: Option<f64>,
    pub pens_scored: u16,
    pub pens_scored_per_90: Option<f64>,
    pub pens_scored_ratio: Option<f64>,
    pub free_kick_shots: u16,
    pub free_kick_shots_per_90: Option<f64>,
    pub minutes_per_goal: Option<f64>,
    pub minutes_per_goal_or_assist: Option<f64>,

    // === Creativity metrics ===
    pub assists: u16,
    pub assists_per_90: Option<f64>,
    pub xa: f64,
    pub xa_per_90: Option<f64>,
    pub chances_created: Option<u16>,
    pub chances_created_per_90: Option<f64>,
    pub clear_cut_chances: u16,
    pub clear_cut_chances_per_90: Option<f64>,
    pub key_passes: u16,
    pub key_passes_per_90: Option<f64>,
    pub op_key_passes: Option<u16>,
    pub op_key_passes_per_90: Option<f64>,
    pub crosses_attempted: u16,
    pub crosses_attempted_per_90: Option<f64>,
    pub crosses_completed: u16,
    pub crosses_completed_per_90: Option<f64>,
    pub cross_completion_ratio: Option<f64>,
    pub op_crosses_attempted: u16,
    pub op_crosses_attempted_per_90: Option<f64>,
    pub op_crosses_completed: u16,
    pub op_crosses_completed_per_90: Option<f64>,
    pub op_cross_completion_ratio: Option<f64>,
    pub minutes_per_assist: Option<f64>,

    // === Transition metrics ===
    pub passes_attempted: u16,
    pub passes_attempted_per_90: Option<f64>,
    pub passes_completed: u16,
    pub passes_completed_per_90: Option<f64>,
    pub pass_completion_ratio: Option<f64>,
    pub progressive_passes: u16,
    pub progressive_passes_per_90: Option<f64>,
    pub dribbles: u16,
    pub dribbles_per_90: Option<f64>,
    pub distance_covered: u32,
    pub distance_covered_per_90: Option<f64>,
    pub sprints: Option<u16>,
    pub sprints_per_90: Option<f64>,
    pub poss_lost: Option<u16>,
    pub poss_lost_per_90: Option<f64>,

    // === Defensive metrics ===
    pub tackles_attempted: u16,
    pub tackles_attempted_per_90: Option<f64>,
    pub tackles_completed: u16,
    pub tackles_completed_per_90: Option<f64>,
    pub tackle_completion_ratio: Option<f64>,
    pub key_tackles: u16,
    pub key_tackles_per_90: Option<f64>,
    pub interceptions: u16,
    pub interceptions_per_90: Option<f64>,
    pub poss_won: Option<u16>,
    pub poss_won_per_90: Option<f64>,
    pub pressures_attempted: u16,
    pub pressures_attempted_per_90: Option<f64>,
    pub pressures_completed: u16,
    pub pressures_completed_per_90: Option<f64>,
    pub pressure_success_ratio: Option<f64>,
    pub blocks: u16,
    pub blocks_per_90: Option<f64>,
    pub shots_blocked: u16,
    pub shots_blocked_per_90: Option<f64>,
    pub clearances: u16,
    pub clearances_per_90: Option<f64>,

    // === Aerial metrics ===
    pub headers_attempted: u16,
    pub headers_attempted_per_90: Option<f64>,
    pub headers_won: u16,
    pub headers_won_per_90: Option<f64>,
    pub headers_lost: Option<u16>,
    pub headers_lost_per_90: Option<f64>,
    pub headers_won_ratio: Option<f64>,
    pub key_headers: Option<u16>,
    pub key_headers_per_90: Option<f64>,

    // === Goalkeeping metrics ===
    pub clean_sheets: u16,
    pub clean_sheets_per_90: Option<f64>,
    pub goals_conceded: u16,
    pub goals_conceded_per_90: Option<f64>,
    pub total_saves: Option<u16>,
    pub total_saves_per_90: Option<f64>,
    pub save_ratio: Option<f64>,
    pub xsv_percent: f64,
    pub xgp: f64,
    pub xgp_per_90: Option<f64>,
    pub saves_held: u16,
    pub saves_held_per_90: Option<f64>,
    pub saves_parried: u16,
    pub saves_parried_per_90: Option<f64>,
    pub saves_tipped: u16,
    pub saves_tipped_per_90: Option<f64>,
    pub pens_faced: u16,
    pub pens_faced_per_90: Option<f64>,
    pub pens_saved: u16,
    pub pens_saved_per_90: Option<f64>,
    pub pens_saved_ratio: Option<f64>,

    // === Discipline metrics ===
    pub fouls_made: u16,
    pub fouls_made_per_90: Option<f64>,
    pub fouls_against: u16,
    pub fouls_against_per_90: Option<f64>,
    pub yellow_cards: u16,
    pub yellow_cards_per_90: Option<f64>,
    pub red_cards: u16,
    pub red_cards_per_90: Option<f64>,
    pub offsides: u16,
    pub offsides_per_90: Option<f64>,
    pub mlg: u16,
    pub mlg_per_90: Option<f64>,

    // === Match impact metrics ===
    pub rating: f64,
    pub pom: u16,
    pub game_win_ratio: Option<f64>,
    pub games_won: u16,
    pub games_drawn: u16,
    pub games_lost: u16,
    pub team_goals: u16,
}

impl Default for Player {
    fn default() -> Self {
        Self {
            unique_id: 0,
            name: String::new(),
            nation: String::new(),
            second_nation: None,
            club: String::new(),
            position: String::new(),
            positions: Vec::new(),
            age: 0,
            height_cm: 0,
            left_foot: Default::default(),
            right_foot: Default::default(),
            current_ability: 0,
            potential_ability: 0,
            transfer_value: Default::default(),
            weekly_wage: Default::default(),
            contract_expires: None,
            appearances: Default::default(),
            minutes: 0,
            goals: 0,
            goals_per_90: None,
            goals_outside_box: 0,
            goals_outside_box_per_90: None,
            xg: 0.0,
            xg_per_90: None,
            npxg: 0.0,
            npxg_per_90: None,
            xg_overperformance: 0.0,
            xg_overperformance_per_90: None,
            xg_per_shot: 0.0,
            shots: 0,
            shots_per_90: None,
            shots_outside_box: None,
            shots_outside_box_per_90: None,
            shots_on_target: 0,
            shots_on_target_per_90: None,
            shots_on_target_ratio: None,
            conversion_ratio: None,
            pens_taken: 0,
            pens_taken_per_90: None,
            pens_scored: 0,
            pens_scored_per_90: None,
            pens_scored_ratio: None,
            free_kick_shots: 0,
            free_kick_shots_per_90: None,
            minutes_per_goal: None,
            minutes_per_goal_or_assist: None,
            assists: 0,
            assists_per_90: None,
            xa: 0.0,
            xa_per_90: None,
            chances_created: None,
            chances_created_per_90: None,
            clear_cut_chances: 0,
            clear_cut_chances_per_90: None,
            key_passes: 0,
            key_passes_per_90: None,
            op_key_passes: None,
            op_key_passes_per_90: None,
            crosses_attempted: 0,
            crosses_attempted_per_90: None,
            crosses_completed: 0,
            crosses_completed_per_90: None,
            cross_completion_ratio: None,
            op_crosses_attempted: 0,
            op_crosses_attempted_per_90: None,
            op_crosses_completed: 0,
            op_crosses_completed_per_90: None,
            op_cross_completion_ratio: None,
            minutes_per_assist: None,
            passes_attempted: 0,
            passes_attempted_per_90: None,
            passes_completed: 0,
            passes_completed_per_90: None,
            pass_completion_ratio: None,
            progressive_passes: 0,
            progressive_passes_per_90: None,
            dribbles: 0,
            dribbles_per_90: None,
            distance_covered: 0,
            distance_covered_per_90: None,
            sprints: None,
            sprints_per_90: None,
            poss_lost: None,
            poss_lost_per_90: None,
            tackles_attempted: 0,
            tackles_attempted_per_90: None,
            tackles_completed: 0,
            tackles_completed_per_90: None,
            tackle_completion_ratio: None,
            key_tackles: 0,
            key_tackles_per_90: None,
            interceptions: 0,
            interceptions_per_90: None,
            poss_won: None,
            poss_won_per_90: None,
            pressures_attempted: 0,
            pressures_attempted_per_90: None,
            pressures_completed: 0,
            pressures_completed_per_90: None,
            pressure_success_ratio: None,
            blocks: 0,
            blocks_per_90: None,
            shots_blocked: 0,
            shots_blocked_per_90: None,
            clearances: 0,
            clearances_per_90: None,
            headers_attempted: 0,
            headers_attempted_per_90: None,
            headers_won: 0,
            headers_won_per_90: None,
            headers_lost: None,
            headers_lost_per_90: None,
            headers_won_ratio: None,
            key_headers: None,
            key_headers_per_90: None,
            clean_sheets: 0,
            clean_sheets_per_90: None,
            goals_conceded: 0,
            goals_conceded_per_90: None,
            total_saves: None,
            total_saves_per_90: None,
            save_ratio: None,
            xsv_percent: 0.0,
            xgp: 0.0,
            xgp_per_90: None,
            saves_held: 0,
            saves_held_per_90: None,
            saves_parried: 0,
            saves_parried_per_90: None,
            saves_tipped: 0,
            saves_tipped_per_90: None,
            pens_faced: 0,
            pens_faced_per_90: None,
            pens_saved: 0,
            pens_saved_per_90: None,
            pens_saved_ratio: None,
            fouls_made: 0,
            fouls_made_per_90: None,
            fouls_against: 0,
            fouls_against_per_90: None,
            yellow_cards: 0,
            yellow_cards_per_90: None,
            red_cards: 0,
            red_cards_per_90: None,
            offsides: 0,
            offsides_per_90: None,
            mlg: 0,
            mlg_per_90: None,
            rating: 0.0,
            pom: 0,
            game_win_ratio: None,
            games_won: 0,
            games_drawn: 0,
            games_lost: 0,
            team_goals: 0,
        }
    }
}
