use serde::{Deserialize, Serialize};

/// FM player with all stats and computed per-90 metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Player {
    // === Identity fields ===
    pub unique_id: u64,
    pub name: String,
    pub nation: String,
    pub second_nation: Option<String>,
    pub club: String,
    pub position: String,

    // === Physical fields ===
    pub age: u8,
    pub height_cm: u16,
    pub left_foot: crate::models::types::FootRating,
    pub right_foot: crate::models::types::FootRating,

    // === Ability fields ===
    pub current_ability: u8,
    pub potential_ability: u8,

    // === Contract fields ===
    pub transfer_value: crate::models::types::TransferValue,
    pub weekly_wage: crate::models::types::Wage,
    pub contract_expires: Option<chrono::NaiveDate>,

    // === Availability ===
    pub appearances: crate::models::types::Appearances,
    pub minutes: u32,

    // === Attacking metrics ===
    pub goals: u16,
    pub goals_per_90: Option<f64>,
    pub goals_outside_box: u16,
    pub goals_outside_box_per_90: Option<f64>,
    pub xg: f64,
    pub xg_per_90: Option<f64>,
    pub npxg: f64,
    pub npxg_per_90: Option<f64>,
    pub xg_overperformance: f64,
    pub xg_overperformance_per_90: Option<f64>,
    pub xg_per_shot: f64,
    pub shots: u16,
    pub shots_per_90: Option<f64>,
    pub shots_outside_box: Option<u16>,
    pub shots_outside_box_per_90: Option<f64>,
    pub shots_on_target: u16,
    pub shots_on_target_per_90: Option<f64>,
    pub shots_on_target_ratio: Option<f64>,
    pub conversion_ratio: Option<f64>,
    pub pens_taken: u16,
    pub pens_taken_per_90: Option<f64>,
    pub pens_scored: u16,
    pub pens_scored_per_90: Option<f64>,
    pub pens_scored_ratio: Option<f64>,
    pub free_kick_shots: u16,
    pub free_kick_shots_per_90: Option<f64>,
    pub minutes_per_goal: Option<f64>,
    pub minutes_per_goal_or_assist: Option<f64>,

    // === Creativity metrics ===
    pub assists: u16,
    pub assists_per_90: Option<f64>,
    pub xa: f64,
    pub xa_per_90: Option<f64>,
    pub chances_created: Option<u16>,
    pub chances_created_per_90: Option<f64>,
    pub clear_cut_chances: u16,
    pub clear_cut_chances_per_90: Option<f64>,
    pub key_passes: u16,
    pub key_passes_per_90: Option<f64>,
    pub op_key_passes: Option<u16>,
    pub op_key_passes_per_90: Option<f64>,
    pub crosses_attempted: u16,
    pub crosses_attempted_per_90: Option<f64>,
    pub crosses_completed: u16,
    pub crosses_completed_per_90: Option<f64>,
    pub cross_completion_ratio: Option<f64>,
    pub op_crosses_attempted: u16,
    pub op_crosses_attempted_per_90: Option<f64>,
    pub op_crosses_completed: u16,
    pub op_crosses_completed_per_90: Option<f64>,
    pub op_cross_completion_ratio: Option<f64>,
    pub minutes_per_assist: Option<f64>,

    // === Transition metrics ===
    pub passes_attempted: u16,
    pub passes_attempted_per_90: Option<f64>,
    pub passes_completed: u16,
    pub passes_completed_per_90: Option<f64>,
    pub pass_completion_ratio: Option<f64>,
    pub progressive_passes: u16,
    pub progressive_passes_per_90: Option<f64>,
    pub dribbles: u16,
    pub dribbles_per_90: Option<f64>,
    pub distance_covered: u32,
    pub distance_covered_per_90: Option<f64>,
    pub sprints: Option<u16>,
    pub sprints_per_90: Option<f64>,
    pub poss_lost: Option<u16>,
    pub poss_lost_per_90: Option<f64>,

    // === Defensive metrics ===
    pub tackles_attempted: u16,
    pub tackles_attempted_per_90: Option<f64>,
    pub tackles_completed: u16,
    pub tackles_completed_per_90: Option<f64>,
    pub tackle_completion_ratio: Option<f64>,
    pub key_tackles: u16,
    pub key_tackles_per_90: Option<f64>,
    pub interceptions: u16,
    pub interceptions_per_90: Option<f64>,
    pub poss_won: Option<u16>,
    pub poss_won_per_90: Option<f64>,
    pub pressures_attempted: u16,
    pub pressures_attempted_per_90: Option<f64>,
    pub pressures_completed: u16,
    pub pressures_completed_per_90: Option<f64>,
    pub pressure_success_ratio: Option<f64>,
    pub blocks: u16,
    pub blocks_per_90: Option<f64>,
    pub shots_blocked: u16,
    pub shots_blocked_per_90: Option<f64>,
    pub clearances: u16,
    pub clearances_per_90: Option<f64>,

    // === Aerial metrics ===
    pub headers_attempted: u16,
    pub headers_attempted_per_90: Option<f64>,
    pub headers_won: u16,
    pub headers_won_per_90: Option<f64>,
    pub headers_lost: Option<u16>,
    pub headers_lost_per_90: Option<f64>,
    pub headers_won_ratio: Option<f64>,
    pub key_headers: Option<u16>,
    pub key_headers_per_90: Option<f64>,

    // === Goalkeeping metrics ===
    pub clean_sheets: u16,
    pub clean_sheets_per_90: Option<f64>,
    pub goals_conceded: u16,
    pub goals_conceded_per_90: Option<f64>,
    pub total_saves: Option<u16>,
    pub total_saves_per_90: Option<f64>,
    pub save_ratio: Option<f64>,
    pub xsv_percent: f64,
    pub xgp: f64,
    pub xgp_per_90: Option<f64>,
    pub saves_held: u16,
    pub saves_held_per_90: Option<f64>,
    pub saves_parried: u16,
    pub saves_parried_per_90: Option<f64>,
    pub saves_tipped: u16,
    pub saves_tipped_per_90: Option<f64>,
    pub pens_faced: u16,
    pub pens_faced_per_90: Option<f64>,
    pub pens_saved: u16,
    pub pens_saved_per_90: Option<f64>,
    pub pens_saved_ratio: Option<f64>,

    // === Discipline metrics ===
    pub fouls_made: u16,
    pub fouls_made_per_90: Option<f64>,
    pub fouls_against: u16,
    pub fouls_against_per_90: Option<f64>,
    pub yellow_cards: u16,
    pub yellow_cards_per_90: Option<f64>,
    pub red_cards: u16,
    pub red_cards_per_90: Option<f64>,
    pub offsides: u16,
    pub offsides_per_90: Option<f64>,
    pub mlg: u16,
    pub mlg_per_90: Option<f64>,

    // === Match impact metrics ===
    pub rating: f64,
    pub pom: u16,
    pub game_win_ratio: Option<f64>,
    pub games_won: u16,
    pub games_drawn: u16,
    pub games_lost: u16,
    pub team_goals: u16,
}
